language: node_js
cache: npm
node_js:
  - '10'
  - '8'

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - beta
    - next
    - /^\d+\.x$/ # build on maintenance branches
    - /^greenkeeper.*$/

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
